title: Digitized 3D scanning/printing for unmatched-precision in novel radiation therapy for early-stage Dupuytren’s disease
logo: /assets/img/profilepic.jpg
#description: Derrick.lee.mailbox@gmail.com
#show_downloads: true
theme: jekyll-theme-minimal
